// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/protobuf/account.proto

package com.iquantex.flink.account.protobuf;

public interface AccountResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.apache.flink.statefun.examples.kafka.AccountResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string retMsg = 1;</code>
   */
  java.lang.String getRetMsg();
  /**
   * <code>string retMsg = 1;</code>
   */
  com.google.protobuf.ByteString
      getRetMsgBytes();
}
