// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/protobuf/account.proto

package com.iquantex.flink.account.protobuf;

public final class Account {
  private Account() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_flink_statefun_examples_kafka_AccountRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_apache_flink_statefun_examples_kafka_AccountRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_flink_statefun_examples_kafka_AccountResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_apache_flink_statefun_examples_kafka_AccountResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$src/main/java/protobuf/account.proto\022(" +
      "org.apache.flink.statefun.examples.kafka" +
      "\"2\n\016AccountRequest\022\023\n\013accountCode\030\001 \001(\t\022" +
      "\013\n\003amt\030\002 \001(\005\"!\n\017AccountResponse\022\016\n\006retMs" +
      "g\030\001 \001(\tB\'\n#com.iquantex.flink.account.pr" +
      "otobufP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_apache_flink_statefun_examples_kafka_AccountRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_apache_flink_statefun_examples_kafka_AccountRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_apache_flink_statefun_examples_kafka_AccountRequest_descriptor,
        new java.lang.String[] { "AccountCode", "Amt", });
    internal_static_org_apache_flink_statefun_examples_kafka_AccountResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_apache_flink_statefun_examples_kafka_AccountResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_apache_flink_statefun_examples_kafka_AccountResponse_descriptor,
        new java.lang.String[] { "RetMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
