// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/protobuf/account.proto

package com.iquantex.flink.account.protobuf;

public interface AccountRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.apache.flink.statefun.examples.kafka.AccountRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string accountCode = 1;</code>
   */
  java.lang.String getAccountCode();
  /**
   * <code>string accountCode = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccountCodeBytes();

  /**
   * <code>int32 amt = 2;</code>
   */
  int getAmt();
}
