// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/protobuf/account.proto

package com.iquantex.flink.account.protobuf;

/**
 * Protobuf type {@code org.apache.flink.statefun.examples.kafka.AccountRequest}
 */
public  final class AccountRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.apache.flink.statefun.examples.kafka.AccountRequest)
    AccountRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AccountRequest.newBuilder() to construct.
  private AccountRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AccountRequest() {
    accountCode_ = "";
    amt_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AccountRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            accountCode_ = s;
            break;
          }
          case 16: {

            amt_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.iquantex.flink.account.protobuf.Account.internal_static_org_apache_flink_statefun_examples_kafka_AccountRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.iquantex.flink.account.protobuf.Account.internal_static_org_apache_flink_statefun_examples_kafka_AccountRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.iquantex.flink.account.protobuf.AccountRequest.class, com.iquantex.flink.account.protobuf.AccountRequest.Builder.class);
  }

  public static final int ACCOUNTCODE_FIELD_NUMBER = 1;
  private volatile java.lang.Object accountCode_;
  /**
   * <code>string accountCode = 1;</code>
   */
  public java.lang.String getAccountCode() {
    java.lang.Object ref = accountCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accountCode_ = s;
      return s;
    }
  }
  /**
   * <code>string accountCode = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAccountCodeBytes() {
    java.lang.Object ref = accountCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accountCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AMT_FIELD_NUMBER = 2;
  private int amt_;
  /**
   * <code>int32 amt = 2;</code>
   */
  public int getAmt() {
    return amt_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAccountCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, accountCode_);
    }
    if (amt_ != 0) {
      output.writeInt32(2, amt_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAccountCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, accountCode_);
    }
    if (amt_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, amt_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.iquantex.flink.account.protobuf.AccountRequest)) {
      return super.equals(obj);
    }
    com.iquantex.flink.account.protobuf.AccountRequest other = (com.iquantex.flink.account.protobuf.AccountRequest) obj;

    boolean result = true;
    result = result && getAccountCode()
        .equals(other.getAccountCode());
    result = result && (getAmt()
        == other.getAmt());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACCOUNTCODE_FIELD_NUMBER;
    hash = (53 * hash) + getAccountCode().hashCode();
    hash = (37 * hash) + AMT_FIELD_NUMBER;
    hash = (53 * hash) + getAmt();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.iquantex.flink.account.protobuf.AccountRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iquantex.flink.account.protobuf.AccountRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iquantex.flink.account.protobuf.AccountRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iquantex.flink.account.protobuf.AccountRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iquantex.flink.account.protobuf.AccountRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iquantex.flink.account.protobuf.AccountRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iquantex.flink.account.protobuf.AccountRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iquantex.flink.account.protobuf.AccountRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iquantex.flink.account.protobuf.AccountRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.iquantex.flink.account.protobuf.AccountRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iquantex.flink.account.protobuf.AccountRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iquantex.flink.account.protobuf.AccountRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.iquantex.flink.account.protobuf.AccountRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.apache.flink.statefun.examples.kafka.AccountRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.apache.flink.statefun.examples.kafka.AccountRequest)
      com.iquantex.flink.account.protobuf.AccountRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iquantex.flink.account.protobuf.Account.internal_static_org_apache_flink_statefun_examples_kafka_AccountRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iquantex.flink.account.protobuf.Account.internal_static_org_apache_flink_statefun_examples_kafka_AccountRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iquantex.flink.account.protobuf.AccountRequest.class, com.iquantex.flink.account.protobuf.AccountRequest.Builder.class);
    }

    // Construct using com.iquantex.flink.account.protobuf.AccountRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      accountCode_ = "";

      amt_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.iquantex.flink.account.protobuf.Account.internal_static_org_apache_flink_statefun_examples_kafka_AccountRequest_descriptor;
    }

    public com.iquantex.flink.account.protobuf.AccountRequest getDefaultInstanceForType() {
      return com.iquantex.flink.account.protobuf.AccountRequest.getDefaultInstance();
    }

    public com.iquantex.flink.account.protobuf.AccountRequest build() {
      com.iquantex.flink.account.protobuf.AccountRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.iquantex.flink.account.protobuf.AccountRequest buildPartial() {
      com.iquantex.flink.account.protobuf.AccountRequest result = new com.iquantex.flink.account.protobuf.AccountRequest(this);
      result.accountCode_ = accountCode_;
      result.amt_ = amt_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.iquantex.flink.account.protobuf.AccountRequest) {
        return mergeFrom((com.iquantex.flink.account.protobuf.AccountRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.iquantex.flink.account.protobuf.AccountRequest other) {
      if (other == com.iquantex.flink.account.protobuf.AccountRequest.getDefaultInstance()) return this;
      if (!other.getAccountCode().isEmpty()) {
        accountCode_ = other.accountCode_;
        onChanged();
      }
      if (other.getAmt() != 0) {
        setAmt(other.getAmt());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.iquantex.flink.account.protobuf.AccountRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.iquantex.flink.account.protobuf.AccountRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object accountCode_ = "";
    /**
     * <code>string accountCode = 1;</code>
     */
    public java.lang.String getAccountCode() {
      java.lang.Object ref = accountCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string accountCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAccountCodeBytes() {
      java.lang.Object ref = accountCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string accountCode = 1;</code>
     */
    public Builder setAccountCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accountCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string accountCode = 1;</code>
     */
    public Builder clearAccountCode() {
      
      accountCode_ = getDefaultInstance().getAccountCode();
      onChanged();
      return this;
    }
    /**
     * <code>string accountCode = 1;</code>
     */
    public Builder setAccountCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      accountCode_ = value;
      onChanged();
      return this;
    }

    private int amt_ ;
    /**
     * <code>int32 amt = 2;</code>
     */
    public int getAmt() {
      return amt_;
    }
    /**
     * <code>int32 amt = 2;</code>
     */
    public Builder setAmt(int value) {
      
      amt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 amt = 2;</code>
     */
    public Builder clearAmt() {
      
      amt_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.apache.flink.statefun.examples.kafka.AccountRequest)
  }

  // @@protoc_insertion_point(class_scope:org.apache.flink.statefun.examples.kafka.AccountRequest)
  private static final com.iquantex.flink.account.protobuf.AccountRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.iquantex.flink.account.protobuf.AccountRequest();
  }

  public static com.iquantex.flink.account.protobuf.AccountRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AccountRequest>
      PARSER = new com.google.protobuf.AbstractParser<AccountRequest>() {
    public AccountRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new AccountRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AccountRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AccountRequest> getParserForType() {
    return PARSER;
  }

  public com.iquantex.flink.account.protobuf.AccountRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

