// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/greeter.proto

package com.baozi.message;

public interface GreetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GreetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string who = 1;</code>
   */
  java.lang.String getWho();
  /**
   * <code>string who = 1;</code>
   */
  com.google.protobuf.ByteString
      getWhoBytes();
}
