// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/greeter.proto

package com.baozi.message;

public interface GreetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GreetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string who = 1;</code>
   */
  java.lang.String getWho();
  /**
   * <code>string who = 1;</code>
   */
  com.google.protobuf.ByteString
      getWhoBytes();

  /**
   * <code>string greeting = 2;</code>
   */
  java.lang.String getGreeting();
  /**
   * <code>string greeting = 2;</code>
   */
  com.google.protobuf.ByteString
      getGreetingBytes();
}
